name: Smoke test. Check migrations

on: [push]

jobs:
  main-job:
    runs-on: ubuntu-latest
    container: python:3.10.8-bullseye
    steps:
    - uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: 5.7.27
        mysql database: derzn
        mysql password: testpass
        mysql user: testuser
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py migrate
      env:
        SECRET_KEY: asdaaskdw9u2r4lfkjd32
        DEBUG: true
        ALLOWED_HOSTS: '*'
        DB_URL: mysql://testuser:testpass@localhost:3306/derzn
        BASE_URL: /
        EMAIL_HOST: localhost
        EMAIL_PORT: 5822
        EMAIL_HOST_USER: admin
        EMAIL_HOST_PASSWORD: somepass
        EMAIL_USE_TLS: false
        EMAIL_USE_SSL: false
